export const filters = [
  { make: "AC", models: ["All Models", "428", "Aceca", "Shelby Cobra"] },
  {
    make: "Acura",
    models: [
      "All Models",
      "CL",
      "ILX",
      "ILX Hybrid",
      "Integra",
      "Legend",
      "MDX",
      "MDX Sport Hybrid",
      "NSX",
      "RDX",
      "RL",
      "RLX",
      "RLX Sport Hybrid",
      "RSX",
      "TL",
      "TLX",
      "TSX",
      "ZDX",
    ],
  },
  {
    make: "Alfa Romeo",
    models: [
      "All Models",
      "164",
      "1750",
      "1900",
      "2000",
      "2600",
      "4C",
      "4C Spider",
      "8c Competizione",
      "Alfetta",
      "GTV",
      "Giulia",
      "Giulietta",
      "Montreal",
      "Spider",
      "Sprint",
      "Stelvio",
      "Tonale",
    ],
  },
  { make: "Am General", models: ["All Models", "Hummer"] },
  {
    make: "American Motors",
    models: [
      "All Models",
      "Ambassador",
      "Classic",
      "Encore",
      "Hornet",
      "Marlin",
      "Matador",
      "Rambler",
      "Rogue",
    ],
  },
  {
    make: "Aston Martin",
    models: [
      "All Models",
      "DB AR1 Zagato",
      "DB11",
      "DB12",
      "DB2/4",
      "DB4",
      "DB6",
      "DB7",
      "DB7 Vantage",
      "DB9",
      "DBS",
      "DBX",
      "Lagonda",
      "Rapide",
      "Rapide S",
      "V12 Vanquish",
      "V12 Vantage",
      "V12 Vantage S",
      "V8 Vantage",
      "V8 Vantage S",
      "Vanquish",
      "Vantage",
      "Vantage GT",
      "Virage",
      "Volante",
      "Zagato",
    ],
  },
  {
    make: "Auburn",
    models: [
      "All Models",
      "Model A",
      "Model B",
      "Model H",
      "Model L",
      "Model S",
      "Model T",
      "Model X",
      "Model Y",
    ],
  },
  {
    make: "Audi",
    models: [
      "All Models",
      "100",
      "200",
      "A3",
      "A3 e-tron",
      "A4",
      "A4 allroad",
      "A5",
      "A5 Sportback",
      "A6",
      "A6 allroad",
      "A7",
      "A7 e",
      "A8",
      "A8 e",
      "Cabriolet",
      "GT",
      "Q3",
      "Q4 e-tron",
      "Q4 e-tron Sportback",
      "Q5",
      "Q5 Sportback",
      "Q5 e",
      "Q5 hybrid",
      "Q7",
      "Q8",
      "Q8 e-tron",
      "Q8 e-tron Sportback",
      "R8",
      "RS 3",
      "RS 4",
      "RS 5",
      "RS 6 Avant",
      "RS 7",
      "RS Q8",
      "RS e-tron GT",
      "RS6",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "SQ5",
      "SQ5 Sportback",
      "SQ7",
      "SQ8",
      "SQ8 e-tron",
      "TT",
      "TT RS",
      "TTS",
      "allroad",
      "e-tron",
      "e-tron GT",
      "e-tron S",
      "e-tron S Sportback",
      "e-tron Sportback",
    ],
  },
  { make: "Austin", models: ["All Models", "Cooper", "Mini"] },
  {
    make: "Austin-Healey",
    models: [
      "All Models",
      "100",
      "100-6",
      "100M",
      "3000",
      "3000 Mk II",
      "3000 Mk III",
      "Sprite",
    ],
  },
  { make: "Avanti Motors", models: ["All Models", "Avanti", "Avanti II"] },
  {
    make: "BMW",
    models: [
      "All Models",
      "1 Series M",
      "128",
      "135",
      "1500",
      "1600",
      "1800",
      "2000",
      "2002",
      "228",
      "228 Gran Coupe",
      "230",
      "2500",
      "2600",
      "3",
      "318",
      "320",
      "3200",
      "323",
      "325",
      "328",
      "328 Gran Turismo",
      "328d",
      "330",
      "330 Gran Turismo",
      "330e",
      "335",
      "335 Gran Turismo",
      "340",
      "340 Gran Turismo",
      "428",
      "428 Gran Coupe",
      "430",
      "430 Gran Coupe",
      "435",
      "435 Gran Coupe",
      "440",
      "440 Gran Coupe",
      "525",
      "528",
      "530",
      "530e",
      "535",
      "535 Gran Turismo",
      "535d",
      "540",
      "550",
      "550 Gran Turismo",
      "600",
      "640",
      "640 Gran Coupe",
      "640 Gran Turismo",
      "645",
      "650",
      "650 Gran Coupe",
      "740",
      "740e",
      "745",
      "745e",
      "750",
      "750e",
      "760",
      "840",
      "840 Gran Coupe",
      "850",
      "ALPINA B7",
      "ALPINA B8 Gran Coupe",
      "ALPINA XB7",
      "ActiveHybrid 3",
      "M",
      "M2",
      "M235",
      "M235 Gran Coupe",
      "M240",
      "M3",
      "M340",
      "M4",
      "M440",
      "M440 Gran Coupe",
      "M5",
      "M550",
      "M6",
      "M760",
      "M8",
      "M8 Gran Coupe",
      "M850",
      "M850 Gran Coupe",
      "X1",
      "X2",
      "X3",
      "X3 M",
      "X3 PHEV",
      "X4",
      "X4 M",
      "X5",
      "X5 M",
      "X5 PHEV",
      "X5 eDrive",
      "X6",
      "X6 M",
      "X7",
      "XM",
      "Z3",
      "Z4",
      "Z4 M",
      "Z8",
      "i3",
      "i4 Gran Coupe",
      "i5",
      "i7",
      "i8",
      "iX",
    ],
  },
  {
    make: "Bentley",
    models: [
      "All Models",
      "Arnage",
      "Azure",
      "Bentayga",
      "Bentayga EWB",
      "Bentayga Hybrid",
      "Brooklands",
      "Continental",
      "Continental Flying Spur",
      "Continental GT",
      "Continental GTC",
      "Continental Supersports",
      "Corniche",
      "Eight",
      "Flying Spur",
      "Flying Spur Hybrid",
      "Mark VI",
      "Mulsanne",
      "R-Type",
      "R-Type Continental",
      "S1",
      "S2",
      "S3",
      "T1",
    ],
  },
  { make: "Bremen", models: ["All Models", "Mini Mark"] },
  { make: "Bricklin", models: ["All Models", "SV-1"] },
  {
    make: "Bugatti",
    models: ["All Models", "Chiron", "Veyron", "Veyron 16.4"],
  },
  {
    make: "Buick",
    models: [
      "All Models",
      "California",
      "Cascada",
      "Century",
      "Electra",
      "Electra 225",
      "Enclave",
      "Encore",
      "Encore GX",
      "Envision",
      "Envista",
      "GS",
      "GS 350",
      "GS 400",
      "GS 455",
      "GranSport",
      "LaCrosse",
      "LeSabre",
      "Limited",
      "Lucerne",
      "Master",
      "Model 27",
      "Model B",
      "Model H",
      "Model S",
      "Park Avenue",
      "Rainier",
      "Reatta",
      "Regal",
      "Regal Sportback",
      "Regal TourX",
      "Rendezvous",
      "Riviera",
      "Roadmaster",
      "Series 40",
      "Series 50",
      "Series 60",
      "Skylark",
      "Special",
      "Sport Wagon",
      "Standard",
      "Super",
      "Terraza",
      "Verano",
      "Wildcat",
    ],
  },
  {
    make: "Cadillac",
    models: [
      "All Models",
      "ATS",
      "ATS-V",
      "Allante",
      "Brougham",
      "CT4",
      "CT4-V",
      "CT5",
      "CT5-V",
      "CT6",
      "CT6 PLUG-IN",
      "CT6-V",
      "CTS",
      "CTS-V",
      "Calais",
      "Custom",
      "DTS",
      "DeVille",
      "ELR",
      "Eldorado",
      "Escalade",
      "Escalade ESV",
      "Escalade EXT",
      "Escalade Hybrid",
      "Fleetwood",
      "LYRIQ",
      "Model A",
      "Model B",
      "Model H",
      "Model L",
      "Model S",
      "Model T",
      "SRX",
      "STS",
      "Series 60",
      "Series 62",
      "Series 70",
      "Seville",
      "Type 57",
      "V-16",
      "XLR",
      "XT4",
      "XT5",
      "XT6",
      "XTS",
    ],
  },
  {
    make: "Chevrolet",
    models: [
      "All Models",
      "150",
      "1500",
      "210",
      "2500",
      "3100",
      "3200",
      "3500",
      "3600",
      "Apache",
      "Astro",
      "Avalanche",
      "Aveo",
      "Bel Air",
      "Biscayne",
      "Blazer",
      "Blazer EV",
      "Bolt EUV",
      "Bolt EV",
      "Brookwood",
      "C10/K10",
      "C20/K20",
      "C30/K30",
      "Camaro",
      "Cameo Carrier",
      "Caprice",
      "Caprice Classic",
      "Captiva Sport",
      "Cavalier",
      "Chevelle",
      "Chevy II",
      "City Express",
      "Classic",
      "Cobalt",
      "Colorado",
      "Confederate",
      "Corvair",
      "Corvette",
      "Corvette E-Ray",
      "Corvette Stingray",
      "Cosworth Vega",
      "Cruze",
      "Cruze Limited",
      "Deluxe",
      "El Camino",
      "Equinox",
      "Equinox EV",
      "Express 1500",
      "Express 2500",
      "Express 3500",
      "Fleetline",
      "Fleetmaster",
      "HHR",
      "Impala",
      "Impala Limited",
      "Independence",
      "Lumina",
      "Malibu",
      "Malibu Classic",
      "Malibu Hybrid",
      "Malibu Limited",
      "Malibu Maxx",
      "Master",
      "Master Deluxe",
      "Metro",
      "Monte Carlo",
      "Nomad",
      "Nova",
      "Panel",
      "Pickup Truck",
      "Prizm",
      "Roadster",
      "S-10",
      "S-10 Blazer",
      "SS",
      "SSR",
      "Sedan Delivery",
      "Silverado 1500",
      "Silverado 1500 Hybrid",
      "Silverado 1500 LD",
      "Silverado 1500 Limited",
      "Silverado 2500",
      "Silverado 3500",
      "Silverado EV",
      "Sonic",
      "Spark",
      "Spark EV",
      "Special Deluxe",
      "Sprint",
      "Standard",
      "Stylemaster",
      "Suburban",
      "Tahoe",
      "Tahoe Hybrid",
      "Tracker",
      "TrailBlazer EXT",
      "Trailblazer",
      "Traverse",
      "Traverse Limited",
      "Trax",
      "Uplander",
      "Van",
      "Vega",
      "Venture",
      "Volt",
    ],
  },
  {
    make: "Chrysler",
    models: [
      "All Models",
      "200",
      "300",
      "300C",
      "300M",
      "Aspen",
      "Concorde",
      "Cordoba",
      "Crossfire",
      "E Class",
      "F-58",
      "Fifth Avenue",
      "Grand Voyager",
      "Imperial",
      "Laser",
      "LeBaron",
      "New Yorker",
      "Newport",
      "PT Cruiser",
      "Pacifica",
      "Pacifica Hybrid",
      "Prowler",
      "Saratoga",
      "Sebring",
      "TC by Maserati",
      "Town &amp; Country",
      "Voyager",
    ],
  },
  { make: "Citroen", models: ["All Models", "2CV", "DS19", "DS21"] },
  {
    make: "Datsun",
    models: [
      "All Models",
      "110",
      "1500",
      "1600",
      "2000",
      "210",
      "240Z",
      "260Z",
      "280Z",
      "280ZX",
      "300ZX",
      "510",
      "Maxima",
      "Sentra",
    ],
  },
  { make: "DeTomaso", models: ["All Models", "Mangusta", "Pantera"] },
  { make: "Delorean", models: ["All Models", "DMC-12"] },
  {
    make: "Desoto",
    models: ["All Models", "Custom", "DeLuxe", "Firedome", "Fireflite", "SC"],
  },
  {
    make: "Dodge",
    models: [
      "All Models",
      "330",
      "440",
      "600",
      "A100",
      "Aspen",
      "Avenger",
      "B-Series",
      "Caliber",
      "Caravan",
      "Challenger",
      "Charger",
      "Coronet",
      "Custom",
      "D100",
      "D150",
      "D2",
      "D250",
      "D350",
      "Dakota",
      "Dart",
      "Deluxe",
      "Diplomat",
      "Durango",
      "Grand Caravan",
      "Hornet",
      "Intrepid",
      "Journey",
      "Lancer",
      "Li&#39;l Red Express",
      "Magnum",
      "Matador",
      "Meadowbrook",
      "Mirada",
      "Monaco",
      "Neon",
      "Nitro",
      "Panel",
      "Pickup Truck",
      "Polara",
      "Power Wagon",
      "Raider",
      "Ram 1500",
      "Ram 2500",
      "Ram 3500",
      "Ram Van",
      "Ram Wagon",
      "Ramcharger",
      "Royal",
      "SRT Viper",
      "Shadow",
      "Special",
      "Sprinter",
      "Standard",
      "Stealth",
      "Stratus",
      "Suburban",
      "Van",
      "Victory",
      "Viper",
      "W250",
      "W350",
    ],
  },
  { make: "Edsel", models: ["All Models", "Corsair", "Ranger", "Villager"] },
  { make: "Essex", models: ["All Models", "Model A", "Super Six"] },
  { make: "Excalibur", models: ["All Models", "Series II", "Series VI"] },
  {
    make: "FIAT",
    models: [
      "All Models",
      "124",
      "124 Spider",
      "128",
      "1500",
      "1900",
      "500",
      "500C",
      "500L",
      "500X",
      "500e",
      "600",
      "850",
      "Dino 2400",
      "Pininfarina",
      "Spider 2000",
      "X1/9",
    ],
  },
  {
    make: "Facel-Vega",
    models: ["All Models", "FV3B", "Facel II", "Facellia"],
  },
  {
    make: "Ferrari",
    models: [
      "All Models",
      "296 GTB",
      "296 GTS",
      "308",
      "328",
      "330",
      "348",
      "360 Modena",
      "360 Spider",
      "365",
      "400i",
      "456 M",
      "458 Italia",
      "458 Speciale",
      "458 Spider",
      "488 GTB",
      "488 Pista",
      "488 Pista Spider",
      "488 Spider",
      "512",
      "512 M",
      "512 TR",
      "550 Maranello",
      "575 M",
      "599 GTB Fiorano",
      "599 GTO",
      "612 Scaglietti",
      "812 Competizione",
      "812 GTS",
      "812 Superfast",
      "California",
      "Dino",
      "F12berlinetta",
      "F12tdf",
      "F355",
      "F40",
      "F430",
      "F8 Spider",
      "F8 Tributo",
      "FF",
      "GT",
      "GTC4Lusso",
      "GTO",
      "LaFerrari",
      "Mondial",
      "Mondial t",
      "Portofino",
      "Portofino M",
      "Roma",
      "SF90 Spider",
      "SF90 Stradale",
      "Superamerica",
      "Testarossa",
    ],
  },
  { make: "Fisker", models: ["All Models", "Karma", "Ocean"] },
  {
    make: "Ford",
    models: [
      "All Models",
      "Aerostar",
      "Bronco",
      "Bronco II",
      "Bronco Sport",
      "Business Coupe",
      "C-Max Energi",
      "C-Max Hybrid",
      "Club Sedan",
      "Club Wagon",
      "Contour",
      "Country Squire",
      "Coupe",
      "Crestline",
      "Crown Victoria",
      "Custom",
      "Customline",
      "Deluxe",
      "E-Transit",
      "E100",
      "E150",
      "E250",
      "E350",
      "E350 Super Duty",
      "EcoSport",
      "Edge",
      "Elite",
      "Escape",
      "Escape Hybrid",
      "Escape PHEV",
      "Escort",
      "Excursion",
      "Expedition",
      "Expedition EL",
      "Expedition Max",
      "Explorer",
      "Explorer Sport",
      "Explorer Sport Trac",
      "F-150",
      "F-150 Lightning",
      "F-250",
      "F-350",
      "F-450",
      "F1",
      "F100",
      "F2",
      "Fairlane",
      "Fairlane 500",
      "Falcon",
      "Fiesta",
      "Five Hundred",
      "Flex",
      "Focus",
      "Focus Electric",
      "Focus RS",
      "Focus ST",
      "Freestar",
      "Freestyle",
      "Fusion",
      "Fusion Energi",
      "Fusion Hybrid",
      "Futura",
      "GT",
      "GT40",
      "Galaxie",
      "Galaxie 500",
      "Galaxie 500 XL",
      "Gran Torino",
      "LTD",
      "Maverick",
      "Model A",
      "Model B",
      "Model S",
      "Model T",
      "Mustang",
      "Mustang Mach-E",
      "Mustang Shelby GT",
      "Panel",
      "Parklane",
      "Phaeton",
      "Pickup Truck",
      "Probe",
      "Ranch",
      "Ranchero",
      "Ranger",
      "Roadster",
      "Sedan Delivery",
      "Sedan Police Interceptor",
      "Shelby GT350",
      "Shelby GT350R",
      "Shelby GT500",
      "Sunliner",
      "Super Deluxe",
      "Taurus",
      "Taurus X",
      "Thunderbird",
      "Torino",
      "Transit Connect",
      "Transit-150",
      "Transit-250",
      "Transit-350",
      "Tudor",
      "Utility Police Interceptor",
      "Van",
      "Victoria",
      "Windstar",
    ],
  },
  { make: "Franklin", models: ["All Models", "Model H"] },
  { make: "GAZ", models: ["All Models", "M20"] },
  {
    make: "GMC",
    models: [
      "All Models",
      "1500",
      "2500",
      "3500",
      "Acadia",
      "Acadia Limited",
      "Caballero",
      "Canyon",
      "Envoy",
      "Envoy XL",
      "Envoy XUV",
      "HUMMER EV",
      "HUMMER EV SUV",
      "Jimmy",
      "Panel",
      "Pickup Truck",
      "Safari",
      "Savana 1500",
      "Savana 2500",
      "Savana 3500",
      "Sierra 1500",
      "Sierra 1500 Hybrid",
      "Sierra 1500 Limited",
      "Sierra 2500",
      "Sierra 3500",
      "Sonoma",
      "Sprint",
      "Suburban",
      "Terrain",
      "Van",
      "Yukon",
      "Yukon Hybrid",
      "Yukon XL",
    ],
  },
  {
    make: "Genesis",
    models: [
      "All Models",
      "Electrified G80",
      "Electrified GV70",
      "G70",
      "G80",
      "G90",
      "GV60",
      "GV70",
      "GV80",
    ],
  },
  { make: "Geo", models: ["All Models", "Metro", "Prizm", "Tracker"] },
  {
    make: "Honda",
    models: [
      "All Models",
      "600",
      "Accord",
      "Accord Crosstour",
      "Accord Hybrid",
      "Accord Plug-In Hybrid",
      "CR-V",
      "CR-V Hybrid",
      "CR-Z",
      "Civic",
      "Civic Hybrid",
      "Civic Si",
      "Civic Type R",
      "Clarity Plug-In Hybrid",
      "Crosstour",
      "Element",
      "Fit",
      "HR-V",
      "Insight",
      "Odyssey",
      "Passport",
      "Pilot",
      "Prelude",
      "Prologue",
      "Ridgeline",
      "S2000",
      "del Sol",
    ],
  },
  {
    make: "Hudson",
    models: [
      "All Models",
      "Commodore",
      "Custom",
      "DeLuxe",
      "DeLuxe Six",
      "Eight",
      "Hornet",
      "Model 54",
      "Pacemaker",
      "Panel",
      "Pickup Truck",
      "Standard",
      "Super",
      "Super Eight",
      "Super Jet",
      "Super Six",
      "Traveler",
    ],
  },
  {
    make: "Hummer",
    models: ["All Models", "H1", "H1 Alpha", "H2", "H3", "H3T"],
  },
  {
    make: "Hupmobile",
    models: ["All Models", "Model H", "Model S", "Skylark"],
  },
  {
    make: "Hyundai",
    models: [
      "All Models",
      "Accent",
      "Azera",
      "Elantra",
      "Elantra GT",
      "Elantra HEV",
      "Elantra N",
      "Elantra Touring",
      "Entourage",
      "Equus",
      "Genesis",
      "Genesis Coupe",
      "IONIQ 5",
      "IONIQ 5 N",
      "IONIQ 6",
      "IONIQ EV",
      "IONIQ Hybrid",
      "IONIQ Plug-In Hybrid",
      "Kona",
      "Kona EV",
      "Kona N",
      "NEXO",
      "Palisade",
      "Santa Cruz",
      "Santa Fe",
      "Santa Fe HEV",
      "Santa Fe Plug-In Hybrid",
      "Santa Fe Sport",
      "Santa Fe XL",
      "Sonata",
      "Sonata Hybrid",
      "Sonata Plug-In Hybrid",
      "Tiburon",
      "Tucson",
      "Tucson Hybrid",
      "Tucson Plug-In Hybrid",
      "Veloster",
      "Veloster N",
      "Venue",
      "Veracruz",
      "XG350",
    ],
  },
  { make: "INEOS", models: ["All Models", "Grenadier"] },
  {
    make: "INFINITI",
    models: [
      "All Models",
      "EX35",
      "EX37",
      "FX35",
      "FX37",
      "FX45",
      "FX50",
      "G20",
      "G25",
      "G25x",
      "G35",
      "G35x",
      "G37",
      "G37x",
      "I30",
      "I35",
      "IPL G",
      "JX35",
      "M30",
      "M35",
      "M35h",
      "M35x",
      "M37",
      "M37x",
      "M45",
      "M45x",
      "M56",
      "M56x",
      "Q40",
      "Q45",
      "Q50",
      "Q50 Hybrid",
      "Q60",
      "Q70",
      "Q70L",
      "Q70h",
      "QX30",
      "QX4",
      "QX50",
      "QX55",
      "QX56",
      "QX60",
      "QX60 Hybrid",
      "QX70",
      "QX80",
    ],
  },
  {
    make: "International",
    models: [
      "All Models",
      "KB-5",
      "M",
      "MXT",
      "Pickup Truck",
      "Scout",
      "Scout II",
      "Travelall",
    ],
  },
  {
    make: "Isuzu",
    models: [
      "All Models",
      "Amigo",
      "Ascender",
      "Axiom",
      "Pickup Truck",
      "Rodeo",
      "Trooper",
      "VehiCROSS",
      "i-350",
      "i-370",
    ],
  },
  {
    make: "Jaguar",
    models: [
      "All Models",
      "340",
      "420",
      "E-PACE",
      "E-Type",
      "F-PACE",
      "F-TYPE",
      "I-PACE",
      "Mark II",
      "Mark IV",
      "Mark V",
      "Mark VII",
      "Mark VIII",
      "S-Type",
      "Vanden Plas",
      "X-Type",
      "XE",
      "XE SV",
      "XF",
      "XJ",
      "XJ12",
      "XJ6",
      "XJ8",
      "XJR",
      "XJR-S",
      "XJS",
      "XK",
      "XK 120",
      "XK 140",
      "XK 150",
      "XK8",
      "XKE",
      "XKR",
    ],
  },
  {
    make: "Jeep",
    models: [
      "All Models",
      "CJ",
      "CJ-5",
      "CJ-7",
      "Cherokee",
      "Comanche",
      "Commander",
      "Commando",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Cherokee 4xe",
      "Grand Cherokee L",
      "Grand Cherokee WK",
      "Grand Wagoneer",
      "Grand Wagoneer L",
      "Jeepster",
      "Liberty",
      "New Compass",
      "Patriot",
      "Renegade",
      "Scrambler",
      "Wagoneer",
      "Wagoneer L",
      "Wrangler",
      "Wrangler 4xe",
      "Wrangler JK",
      "Wrangler JK Unlimited",
      "Wrangler Unlimited",
      "Wrangler Unlimited 4xe",
    ],
  },
  {
    make: "Jensen",
    models: ["All Models", "541", "GT", "Interceptor", "Jensen-Healey"],
  },
  {
    make: "Kaiser",
    models: [
      "All Models",
      "Darrin",
      "Henry J",
      "Jeep M715",
      "Manhattan",
      "Special",
    ],
  },
  { make: "Karma", models: ["All Models", "GS-6", "Revero", "Revero GT"] },
  {
    make: "Kia",
    models: [
      "All Models",
      "Amanti",
      "Borrego",
      "Cadenza",
      "Carnival",
      "EV6",
      "EV9",
      "Forte",
      "Forte Koup",
      "K5",
      "K900",
      "Niro",
      "Niro EV",
      "Niro Plug-In Hybrid",
      "Optima",
      "Optima Hybrid",
      "Optima Plug-In Hybrid",
      "Rio",
      "Rio5",
      "Rondo",
      "Sedona",
      "Seltos",
      "Sephia",
      "Sorento",
      "Sorento Hybrid",
      "Sorento Plug-In Hybrid",
      "Soul",
      "Soul EV",
      "Spectra",
      "Spectra5",
      "Sportage",
      "Sportage Hybrid",
      "Sportage Plug-In Hybrid",
      "Stinger",
      "Telluride",
    ],
  },
  { make: "Koenigsegg", models: ["All Models", "Regera"] },
  { make: "LaSalle", models: ["All Models", "328", "340", "50"] },
  {
    make: "Lamborghini",
    models: [
      "All Models",
      "400 GT",
      "Aventador",
      "Aventador S",
      "Aventador SVJ",
      "Countach",
      "Diablo",
      "Gallardo",
      "Huracan",
      "Huracan EVO",
      "Huracan STO",
      "Huracan Sterrato",
      "Huracan Tecnica",
      "Jalpa",
      "Murcielago",
      "Silhouette",
      "Urus",
    ],
  },
  { make: "Lancia", models: ["All Models", "Aurelia", "Scorpion", "Zagato"] },
  {
    make: "Land Rover",
    models: [
      "All Models",
      "Defender",
      "Discovery",
      "Discovery Sport",
      "LR2",
      "LR3",
      "LR4",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
      "Series II",
      "Series III",
    ],
  },
  {
    make: "Lexus",
    models: [
      "All Models",
      "CT 200h",
      "ES 250",
      "ES 300",
      "ES 300h",
      "ES 330",
      "ES 350",
      "GS 200t",
      "GS 300",
      "GS 350",
      "GS 400",
      "GS 430",
      "GS 450h",
      "GS 460",
      "GS F",
      "GX 460",
      "GX 470",
      "GX 550",
      "HS 250h",
      "IS 200t",
      "IS 250",
      "IS 250C",
      "IS 300",
      "IS 350",
      "IS 350C",
      "IS 500",
      "IS-F",
      "LC 500",
      "LC 500h",
      "LFA",
      "LS 400",
      "LS 430",
      "LS 460",
      "LS 500",
      "LS 500h",
      "LS 600h L",
      "LX 450",
      "LX 470",
      "LX 570",
      "LX 600",
      "NX 200t",
      "NX 250",
      "NX 300",
      "NX 300h",
      "NX 350",
      "NX 350h",
      "NX 450h+",
      "RC 200t",
      "RC 300",
      "RC 350",
      "RC F",
      "RX 300",
      "RX 330",
      "RX 350",
      "RX 350L",
      "RX 350h",
      "RX 400h",
      "RX 450h",
      "RX 450h+",
      "RX 450hL",
      "RX 500h",
      "RZ 300e",
      "RZ 450e",
      "SC 300",
      "SC 400",
      "SC 430",
      "TX 350",
      "TX 500h",
      "TX 550h+",
      "UX 200",
      "UX 250h",
      "UX 300h",
    ],
  },
  {
    make: "Lincoln",
    models: [
      "All Models",
      "Aviator",
      "Blackwood",
      "Capri",
      "Continental",
      "Corsair",
      "Custom",
      "LS",
      "MKC",
      "MKS",
      "MKT",
      "MKX",
      "MKZ",
      "MKZ Hybrid",
      "Mark II",
      "Mark III",
      "Mark IV",
      "Mark LT",
      "Mark V",
      "Mark VI",
      "Mark VII",
      "Mark VIII",
      "Model L",
      "Nautilus",
      "Navigator",
      "Navigator L",
      "Premiere",
      "Town Car",
      "Zephyr",
    ],
  },
  {
    make: "Lotus",
    models: [
      "All Models",
      "Elan",
      "Eletre",
      "Elise",
      "Elite",
      "Emira",
      "Esprit",
      "Esprit V8",
      "Evora",
      "Evora 400",
      "Evora GT",
    ],
  },
  { make: "Lucid", models: ["All Models", "Air"] },
  {
    make: "MG",
    models: [
      "All Models",
      "MGA",
      "MGB",
      "Midget",
      "TC Roadster",
      "TD",
      "TF",
      "YT",
    ],
  },
  {
    make: "MINI",
    models: [
      "All Models",
      "Clubman",
      "Convertible",
      "Cooper",
      "Cooper Clubman",
      "Cooper Countryman",
      "Cooper S",
      "Cooper S Clubman",
      "Cooper S Countryman",
      "Countryman",
      "Coupe",
      "E Countryman",
      "Hardtop",
      "John Cooper Works GP",
      "Paceman",
      "Roadster",
      "SE Countryman",
      "SE Hardtop",
    ],
  },
  {
    make: "Maserati",
    models: [
      "All Models",
      "228",
      "3500",
      "430",
      "Biturbo",
      "Bora",
      "Coupe",
      "Ghibli",
      "GranCabrio",
      "GranSport",
      "GranTurismo",
      "Grecale",
      "Khamsin",
      "Levante",
      "MC20",
      "Mistral",
      "Quattroporte",
      "Sebring",
      "Spyder",
    ],
  },
  {
    make: "Maybach",
    models: ["All Models", "Landaulet", "Type 57", "Type 62"],
  },
  {
    make: "Mazda",
    models: [
      "All Models",
      "1800",
      "323",
      "626",
      "929",
      "B2300",
      "B2500",
      "B3000",
      "B4000",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-50",
      "CX-7",
      "CX-70",
      "CX-70 PHEV",
      "CX-9",
      "CX-90",
      "CX-90 PHEV",
      "MPV",
      "MX-30",
      "MX-30 EV",
      "MX-5 Miata",
      "MX-5 Miata RF",
      "Mazda2",
      "Mazda3",
      "Mazda5",
      "Mazda6",
      "MazdaSpeed Miata MX-5",
      "MazdaSpeed3",
      "Pickup Truck",
      "Protege",
      "Protege5",
      "RX-7",
      "RX-8",
      "Tribute",
    ],
  },
  {
    make: "McLaren",
    models: [
      "All Models",
      "570GT",
      "570S",
      "600LT",
      "620R",
      "650S",
      "675LT",
      "720S",
      "750S",
      "765LT",
      "Artura",
      "Elva",
      "GT",
      "MP4-12C",
      "P1",
      "Senna",
    ],
  },
  {
    make: "Mercedes-Benz",
    models: [
      "All Models",
      "190SL",
      "200",
      "230",
      "240",
      "280SE",
      "280SL",
      "300",
      "300C",
      "320",
      "380SL",
      "450SL",
      "600",
      "A-Class",
      "AMG A 35",
      "AMG C",
      "AMG C 43",
      "AMG C 63",
      "AMG CLA 35",
      "AMG CLA 45",
      "AMG CLE 53",
      "AMG CLS 53",
      "AMG E",
      "AMG E 43",
      "AMG E 53",
      "AMG E 63",
      "AMG EQE",
      "AMG EQS",
      "AMG G",
      "AMG G 63",
      "AMG GLA 35",
      "AMG GLA 45",
      "AMG GLB 35",
      "AMG GLC 43",
      "AMG GLC 63",
      "AMG GLE",
      "AMG GLE 43",
      "AMG GLE 53",
      "AMG GLE 63",
      "AMG GLS 63",
      "AMG GT",
      "AMG GT 43",
      "AMG GT 53",
      "AMG GT 55",
      "AMG GT 63",
      "AMG S",
      "AMG S 63",
      "AMG S 65",
      "AMG SL 43",
      "AMG SL 55",
      "AMG SL 63",
      "AMG SLC 43",
      "C-Class",
      "CL-Class",
      "CLA 250",
      "CLA-Class",
      "CLE 300",
      "CLE 450",
      "CLK-Class",
      "CLS 450",
      "CLS 550",
      "CLS-Class",
      "E-Class",
      "EQB 250",
      "EQB 300",
      "EQB 350",
      "EQE 350",
      "EQE 350+",
      "EQE 500",
      "EQS 450",
      "EQS 450+",
      "EQS 580",
      "G 550 4x4 Squared",
      "G-Class",
      "GL-Class",
      "GLA 250",
      "GLA-Class",
      "GLB 250",
      "GLC 300",
      "GLC 350e",
      "GLC-Class",
      "GLE 350",
      "GLE 400",
      "GLE 450",
      "GLE 450 Plug-In Hybrid",
      "GLE 580",
      "GLE-Class",
      "GLK-Class",
      "GLS 450",
      "GLS 550",
      "GLS 580",
      "M-Class",
      "Maybach EQS 680",
      "Maybach GLS 600",
      "Maybach S",
      "Maybach S 560",
      "Maybach S 580",
      "Maybach S 650",
      "Maybach S 680",
      "Metris",
      "R-Class",
      "S-Class",
      "SL 450",
      "SL 550",
      "SL-Class",
      "SLC 300",
      "SLK-Class",
      "SLR McLaren",
      "SLS AMG",
      "Sprinter",
      "Sprinter 1500",
      "Sprinter 2500",
      "Sprinter 3500",
      "Sprinter 3500XD",
      "Sprinter 4500",
      "eSprinter 2500",
    ],
  },
  {
    make: "Mercury",
    models: [
      "All Models",
      "Brougham",
      "Capri",
      "Colony Park",
      "Comet",
      "Cougar",
      "Custom",
      "Cyclone",
      "Eight",
      "Grand Marquis",
      "Marauder",
      "Mariner",
      "Mariner Hybrid",
      "Marquis",
      "Milan",
      "Montclair",
      "Montego",
      "Monterey",
      "Mountaineer",
      "Mystique",
      "Parklane",
      "Sable",
      "Series 19A",
      "Villager",
      "Voyager",
      "Zephyr",
    ],
  },
  {
    make: "Mitsubishi",
    models: [
      "All Models",
      "3000GT",
      "Diamante",
      "Eclipse",
      "Eclipse Cross",
      "Endeavor",
      "Galant",
      "Lancer",
      "Lancer Evolution",
      "Lancer Sportback",
      "Mirage",
      "Mirage G4",
      "Montero",
      "Montero Sport",
      "Outlander",
      "Outlander PHEV",
      "Outlander Sport",
      "Pickup Truck",
      "Raider",
      "i-MiEV",
    ],
  },
  { make: "Morgan", models: ["All Models", "Plus 4", "Roadster"] },
  { make: "Morris", models: ["All Models", "Mini"] },
  {
    make: "Nash",
    models: [
      "All Models",
      "600",
      "660",
      "960",
      "Ambassador",
      "DeLuxe",
      "Rambler",
      "Special",
      "Standard",
      "Super",
    ],
  },
  {
    make: "Nissan",
    models: [
      "All Models",
      "240SX",
      "280ZX",
      "300ZX",
      "350Z",
      "370Z",
      "ARIYA",
      "Altima",
      "Altima Hybrid",
      "Armada",
      "Cube",
      "Frontier",
      "GT-R",
      "Juke",
      "Kicks",
      "Leaf",
      "Maxima",
      "Murano",
      "Murano CrossCabriolet",
      "Murano Hybrid",
      "NV Cargo",
      "NV Cargo NV1500",
      "NV Cargo NV2500 HD",
      "NV Cargo NV3500 HD",
      "NV Passenger",
      "NV Passenger NV3500 HD",
      "NV200",
      "NX",
      "Pathfinder",
      "Pathfinder Hybrid",
      "Pickup Truck",
      "Quest",
      "Rogue",
      "Rogue Hybrid",
      "Rogue Select",
      "Rogue Sport",
      "Sentra",
      "Titan",
      "Titan XD",
      "Van",
      "Versa",
      "Versa Note",
      "Xterra",
      "Z",
    ],
  },
  {
    make: "Oldsmobile",
    models: [
      "All Models",
      "442",
      "66",
      "76",
      "88",
      "98",
      "Alero",
      "Aurora",
      "Bravada",
      "Calais",
      "Custom",
      "Cutlass",
      "Cutlass Calais",
      "Cutlass Ciera",
      "Cutlass Supreme",
      "Defender",
      "Delmont 88",
      "Dynamic 88",
      "Eighty-Eight",
      "F-85",
      "Fiesta",
      "Intrigue",
      "Limited",
      "Model 54",
      "Model A",
      "Model B",
      "Model F-34",
      "Model H",
      "Model L",
      "Model S",
      "Model X",
      "Ninety-Eight",
      "Silhouette",
      "Special",
      "Starfire",
      "Super 88",
      "Toronado",
      "Vista Cruiser",
    ],
  },
  { make: "Opel", models: ["All Models", "1900", "Caravan", "GT"] },
  {
    make: "Packard",
    models: [
      "All Models",
      "110",
      "115C",
      "120",
      "1600",
      "200",
      "300",
      "626",
      "640",
      "645",
      "740",
      "745",
      "840",
      "900",
      "Cavalier",
      "Clipper",
      "Custom",
      "Deluxe",
      "Eight",
      "LeBaron",
      "Model A",
      "Model B",
      "Model L",
      "Model S",
      "Standard",
      "Super",
      "Super Eight",
    ],
  },
  { make: "Pagani", models: ["All Models", "Huayra"] },
  {
    make: "Panoz",
    models: ["All Models", "AIV Roadster", "Esperante", "Roadster"],
  },
  { make: "Pierce-Arrow", models: ["All Models", "Model 54"] },
  {
    make: "Plymouth",
    models: [
      "All Models",
      "Barracuda",
      "Belvedere",
      "Business",
      "Champ",
      "Coupe",
      "Cranbrook",
      "Cuda",
      "DeLuxe",
      "Duster",
      "Fury",
      "GTX",
      "Grand Voyager",
      "Laser",
      "Model PB",
      "Neon",
      "PA",
      "Pickup Truck",
      "Prowler",
      "Roadrunner",
      "Satellite",
      "Savoy",
      "Scamp",
      "Sebring",
      "Sedan Delivery",
      "Special DeLuxe",
      "Sport Fury",
      "Standard",
      "Suburban",
      "Valiant",
      "Van",
      "Volare",
      "Voyager",
    ],
  },
  { make: "Polestar", models: ["All Models", "1", "2", "3"] },
  {
    make: "Pontiac",
    models: [
      "All Models",
      "2000",
      "Aztek",
      "Bonneville",
      "Catalina",
      "Chieftain",
      "Custom",
      "Deluxe",
      "Deluxe Six",
      "Fiero",
      "Firebird",
      "G3",
      "G5",
      "G6",
      "G8",
      "GTO",
      "Grand Am",
      "Grand Prix",
      "Grand Ville",
      "LeMans",
      "Montana",
      "Montana SV6",
      "Safari",
      "Solstice",
      "Streamliner",
      "Sunbird",
      "Sunfire",
      "Super Deluxe",
      "Tempest",
      "Torrent",
      "Trans Sport",
      "Ventura",
      "Vibe",
    ],
  },
  {
    make: "Porsche",
    models: [
      "All Models",
      "356",
      "718 Boxster",
      "718 Cayman",
      "718 Spyder",
      "911",
      "912",
      "914",
      "918 Spyder",
      "924",
      "928",
      "930",
      "944",
      "968",
      "Boxster",
      "Carrera GT",
      "Cayenne",
      "Cayenne E-Hybrid",
      "Cayenne E-Hybrid Coupe",
      "Cayenne Hybrid",
      "Cayman",
      "Macan",
      "Panamera",
      "Panamera E-Hybrid",
      "Panamera E-Hybrid Sport Turismo",
      "Panamera Hybrid",
      "Panamera Sport Turismo",
      "S90",
      "Taycan",
      "Taycan Cross Turismo",
    ],
  },
  { make: "Qvale", models: ["All Models", "Mangusta"] },
  {
    make: "RAM",
    models: [
      "All Models",
      "1500",
      "1500 Classic",
      "2500",
      "3500",
      "Cargo",
      "ProMaster 1500",
      "ProMaster 2500",
      "ProMaster 2500 Window Van",
      "ProMaster 3500",
      "ProMaster 3500 Window Van",
      "ProMaster City",
    ],
  },
  { make: "Rambler", models: ["All Models", "Custom", "Rogue"] },
  { make: "Renault", models: ["All Models", "R8", "Sport Wagon"] },
  { make: "Rivian", models: ["All Models", "R1S", "R1T"] },
  {
    make: "Rolls-Royce",
    models: [
      "All Models",
      "20/25",
      "Corniche",
      "Cullinan",
      "Dawn",
      "Ghost",
      "Phantom",
      "Phantom Coupe",
      "Phantom Drophead Coupe",
      "Phantom III",
      "Phantom V",
      "Phantom VI",
      "Silver Cloud II",
      "Silver Cloud III",
      "Silver Dawn",
      "Silver Seraph",
      "Silver Shadow",
      "Silver Shadow II",
      "Silver Spirit",
      "Silver Spur",
      "Silver Spur II",
      "Silver Wraith",
      "Silver Wraith II",
      "Spectre",
      "Wraith",
    ],
  },
  {
    make: "Saab",
    models: [
      "All Models",
      "9-2X",
      "9-3",
      "9-5",
      "9-7X",
      "900",
      "96",
      "GT",
      "Monte Carlo",
    ],
  },
  { make: "Saleen", models: ["All Models", "S7"] },
  {
    make: "Saturn",
    models: [
      "All Models",
      "Astra",
      "Aura",
      "Ion",
      "L",
      "LS",
      "Outlook",
      "SC",
      "SL",
      "Sky",
      "Vue",
      "Vue Hybrid",
    ],
  },
  {
    make: "Scion",
    models: ["All Models", "FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD"],
  },
  {
    make: "Studebaker",
    models: [
      "All Models",
      "440",
      "Avanti",
      "Challenger",
      "Champ",
      "Champion",
      "Commander",
      "Golden Hawk",
      "Gran Turismo Hawk",
      "Land Cruiser",
      "Lark",
      "Model A",
      "Model B",
      "Model H",
      "Model L",
      "Pickup Truck",
      "President",
      "Regal",
    ],
  },
  {
    make: "Subaru",
    models: [
      "All Models",
      "1600",
      "1800",
      "Ascent",
      "B9 Tribeca",
      "BRZ",
      "Baja",
      "Crosstrek",
      "Crosstrek Hybrid",
      "Forester",
      "Impreza",
      "Impreza Outback Sport",
      "Impreza WRX",
      "Impreza WRX STi",
      "Legacy",
      "Outback",
      "STI S209",
      "SVX",
      "Solterra",
      "Tribeca",
      "WRX",
      "WRX STI",
      "XV Crosstrek",
      "XV Crosstrek Hybrid",
    ],
  },
  { make: "Sunbeam", models: ["All Models", "Alpine", "Tiger"] },
  {
    make: "Suzuki",
    models: [
      "All Models",
      "Aerio",
      "Equator",
      "Grand Vitara",
      "Kizashi",
      "Reno",
      "SX4",
      "Samurai",
      "Vitara",
      "XL7",
    ],
  },
  {
    make: "Tesla",
    models: [
      "All Models",
      "Cybertruck",
      "Model 3",
      "Model S",
      "Model X",
      "Model Y",
      "Roadster",
    ],
  },
  {
    make: "Toyota",
    models: [
      "All Models",
      "4Runner",
      "86",
      "Avalon",
      "Avalon Hybrid",
      "C-HR",
      "Camry",
      "Camry Hybrid",
      "Camry Solara",
      "Celica",
      "Corolla",
      "Corolla Cross",
      "Corolla Cross Hybrid",
      "Corolla Hatchback",
      "Corolla Hybrid",
      "Corolla iM",
      "Corona",
      "Cressida",
      "Crown",
      "ECHO",
      "FJ Cruiser",
      "GR Corolla",
      "GR Supra",
      "GR86",
      "Grand Highlander",
      "Grand Highlander Hybrid",
      "Highlander",
      "Highlander Hybrid",
      "Land Cruiser",
      "MR2",
      "Matrix",
      "Mirai",
      "Pickup Truck",
      "Previa",
      "Prius",
      "Prius Plug-in",
      "Prius Prime",
      "Prius c",
      "Prius v",
      "RAV4",
      "RAV4 EV",
      "RAV4 Hybrid",
      "RAV4 Prime",
      "Sequoia",
      "Sienna",
      "Supra",
      "T100",
      "Tacoma",
      "Tercel",
      "Tundra",
      "Tundra Hybrid",
      "Van",
      "Venza",
      "Yaris",
      "Yaris Sedan",
      "Yaris iA",
      "bZ4X",
    ],
  },
  {
    make: "Triumph",
    models: [
      "All Models",
      "1800",
      "2000",
      "Spitfire",
      "TR250",
      "TR3",
      "TR4",
      "TR6",
      "TR7",
      "TR8",
    ],
  },
  { make: "VinFast", models: ["All Models", "VF 8"] },
  {
    make: "Volkswagen",
    models: [
      "All Models",
      "1600",
      "Arteon",
      "Atlas",
      "Atlas Cross Sport",
      "Beetle",
      "Beetle (Pre-1980)",
      "CC",
      "Cabrio",
      "Cabriolet",
      "Corrado",
      "Eos",
      "Eurovan",
      "GTI",
      "Golf",
      "Golf Alltrack",
      "Golf GTI",
      "Golf R",
      "Golf SportWagen",
      "ID.4",
      "Jetta",
      "Jetta GLI",
      "Jetta Hybrid",
      "Jetta SportWagen",
      "Karmann Ghia",
      "Microbus",
      "New Beetle",
      "Passat",
      "Phaeton",
      "R32",
      "Rabbit",
      "Routan",
      "Super Beetle",
      "Taos",
      "Thing",
      "Tiguan",
      "Tiguan Limited",
      "Touareg",
      "Touareg 2",
      "Touareg Hybrid",
      "Type 2",
      "Van",
      "Vanagon",
      "e-Golf",
    ],
  },
  {
    make: "Volvo",
    models: [
      "All Models",
      "122",
      "164",
      "1800",
      "240",
      "740",
      "760",
      "850",
      "940",
      "960",
      "C30",
      "C40 Recharge Pure Electric",
      "C70",
      "Coupe",
      "P1800",
      "P1800E",
      "S40",
      "S60",
      "S60 Cross Country",
      "S60 Hybrid",
      "S60 Inscription",
      "S60 Recharge Plug-In Hybrid",
      "S70",
      "S80",
      "S90",
      "S90 Recharge Plug-In Hybrid",
      "V50",
      "V60",
      "V60 Cross Country",
      "V60 Recharge Plug-In Hybrid",
      "V70",
      "V90",
      "V90 Cross Country",
      "XC40",
      "XC40 Recharge Pure Electric",
      "XC60",
      "XC60 Recharge Plug-In Hybrid",
      "XC70",
      "XC90",
      "XC90 Hybrid",
      "XC90 Recharge Plug-In Hybrid",
    ],
  },
  {
    make: "Willys",
    models: [
      "All Models",
      "CJ-5",
      "Jeepster",
      "Maverick",
      "Panel",
      "Pickup Truck",
    ],
  },
  { make: "Yugo", models: ["All Models", "Cabrio"] },
  {
    make: "smart",
    models: ["All Models", "EQ ForTwo", "ForTwo", "ForTwo Electric Drive"],
  },
];

export const distances = [10, 20, 30, 40, 50, 75, 100, 150, 200, 250, 500];
